### ISSUE TITLE
debops.gitlab: After an upgrade to Jessie, GitLab refuses to start or perform operations

### ISSUE THREAD

**Issue by drybjed** [debops/debops-playbooks#106]
For example, running a backup rake in GitLab shows:

```
rake aborted!
LoadError: libicui18n.so.48: cannot open shared object file: No such file or directory - /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0/charlock_holmes-0.6.9.4/charlock_holmes/charlock_holmes.so
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/charlock_holmes-0.6.9.4/lib/charlock_holmes.rb:1:in `<top (required)>'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab-grit-2.6.7/lib/grit.rb:79:in `<top (required)>'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `block in require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:214:in `load_dependency'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/dependencies.rb:229:in `require'
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-5.8.0/lib/gitlab_git.rb:4:in `<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
/var/local/git/gitlab/config/application.rb:6:in `<top (required)>'
/var/local/git/gitlab/Rakefile:5:in `require'
/var/local/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

This might be related to `charlock_holmes` gem, after a quick googling I've found [this GitLab issue](https://github.com/gitlabhq/gitlabhq/issues/8381) which points to [this apparent fix](https://github.com/brianmario/charlock_holmes/issues/7). This should be investigated further to find a way to implement the fix in `debops.gitlab` and other similar roles.

**Comment by drybjed** [comment]
The `debops.gitlab` role was redesigned, this issue is no longer relevant.
